services:
  - type: web
    name: whatsapp-api
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel build
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=8000
    plan: free
